import { ERRORS, WARNINGS, ERROR, WARNING } from './constants.js'

export const defaultConfig = {
  host: null,
  ignoreFiles: [],
  customRules: [],
  rules: {
    'html.brokenLinks': ERROR,
    'html.favicon': ERROR,
    'html.img.alt': ERROR,
    'html.internalLinks': ERROR,
    'html.lang': ERROR,
    'html.linkText': ERROR,
    'html.maxOutboundLinks': WARNING,
    'html.meta.description': ERROR,
    'html.meta.viewport': ERROR,
    'html.missingImages': ERROR,
    'html.noVideo': WARNING,
    'html.tabindex': WARNING,
    'html.title': ERROR,
    'file.maxImageSize': WARNING,
    'folder.htaccess': WARNING,
    'folder.robots': ERROR,
    'folder.sitemap': ERROR,
    'seo.canonical': ERROR,
    'seo.headings': ERROR,
    'seo.uniqueTitle': ERROR,
  },
  display: [ERRORS, WARNINGS],
  failOn: [ERRORS],
}
